routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });

app/Proposal.php
<?php

namespace App;

use App\Traits\Multitenantable;
use App\Traits\Sluggable;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proposal extends Model
{
    use HasFactory;
    use Multitenantable;
    use Sluggable;

    protected $fillable = [
        'name', 'client_id', 'language_id', 'date', 'reference', 'contact_person', 'desc', 'terms',
    ];

    public function sluggable()
    {
        return [
            'source' => 'name',
        ];
    }

    /**
     * The concepts.
     */
    public function concepts()
    {
        return $this->hasMany(\App\ProposalConcept::class);
    }

    /**
     * Get the project.
     */
    public function language()
    {
        return $this->belongsTo(\App\Language::class)->withDefault();
    }

    /**
     * Get the user.
     */
    public function user()
    {
        return $this->belongsTo(\App\User::class)->withDefault();
    }

    /**
     * Get the client.
     */
    public function client()
    {
        return $this->belongsTo(\App\Client::class)->withDefault();
    }

    /*
    Attributes
    */
    public function getTotalAttribute()
    {
        $total = 0;
        foreach ($this->concepts()->get() as $item) {
            $total += $item->price;
        }

        return $total;
    }

    public function getUrlAttribute()
    {
        return '/proposals/'.$this->id.'/'.$this->slug;
    }

    public function getShowDateAttribute()
    {
        return Carbon::parse($this->date)->format('d/m/Y');
    }
}

app/ProposalConcept.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class ProposalConcept extends Model
{
    protected $fillable = [
        'name', 'desc', 'price', 'finish_date', 'order',
    ];

    /**
     * The proposal.
     */
    public function proposal()
    {
        return $this->belongsTo(\App\Proposal::class);
    }

    public function getShowFinishDateAttribute()
    {
        return Carbon::parse($this->finish_date)->format('d/m/Y');
    }
}

app/Http/Controllers/ProposalController.php
<?php

namespace App\Http\Controllers;

use App\ApiCode;
use App\Proposal;
use App\ProposalConcept;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use MarcinOrlowski\ResponseBuilder\ResponseBuilder;

class ProposalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'client_id' => 'required|exists:clients,id',
        ]);

        $item = new Proposal([
            'name' => trim($request->get('name')),
            'client_id' => $request->get('client_id'),
            'language_id' => $request->get('language_id'),
            'desc' => $request->get('desc'),
            'reference' => $request->get('reference'),
            'contact_person' => $request->get('contact_person'),
            'terms' => $request->get('terms'),
            'date' => Carbon::parse($request->get('date'))->format('Y-m-d'),

        ]);
        $item->save();

        // Store concepts
        $concepts = $request->get('concepts');
        foreach ($concepts as $elemento) {
            $concept = new ProposalConcept([
                'name' => $elemento['name'],
                'desc' => $elemento['desc'],
                'finish_date' => Carbon::parse($elemento['finish_date'])->format('Y-m-d'),
                'price' => $elemento['price'],
                'order' => 1,
            ]);
            $item->concepts()->save($concept);
        }

        return ResponseBuilder::success($item);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function show(Proposal $proposal)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function edit(Proposal $proposal)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Proposal $proposal)
    {
        $request->validate([
            'name' => 'required',
            'client_id' => 'required|exists:clients,id',
            'language_id' => 'required|exists:languages,id',
        ]);

        $item = Proposal::find($request->get('id'));
        if ($item) {
            $item->name = trim($request->get('name'));
            $item->client_id = $request->get('client_id');
            $item->language_id = $request->get('language_id');
            $item->desc = $request->get('desc');
            $item->date = Carbon::parse($request->get('date'))->format('Y-m-d');
            $item->terms = $request->get('terms');
            $item->reference = $request->get('reference');
            $item->contact_person = $request->get('contact_person');
            $item->save();

            // Remove old concepts to store new
            $item->concepts()->delete();
            $concepts = $request->get('concepts');
            foreach ($concepts as $elemento) {
                $concept = new ProposalConcept([
                    'name' => $elemento['name'],
                    'desc' => $elemento['desc'],
                    'finish_date' => Carbon::parse($elemento['finish_date'])->format('Y-m-d'),
                    'price' => $elemento['price'],
                    'order' => 1,
                ]);
                $item->concepts()->save($concept);
            }

            return ResponseBuilder::success($item);
        }

        return ResponseBuilder::error(250);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function destroy(Proposal $proposal)
    {
        //
    }

    /**
     * Gets the projects list.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function fetch()
    {
        $collection = [];
        $user = Auth::user();
        foreach (Proposal::orderBy('date', 'desc')->orderBy('name', 'asc')->get() as $item) {
            array_push($collection, [
                'id' => $item->id,
                'name' => $item->name,
                'client' => $item->client->name,
                'total' => currency_format((string) $item->total, $user->currency->code),
                'reference' => $item->reference,
                'date' => Carbon::parse($item->date)->format('d/m/Y'),
                'url' => $item->url,
            ]);
        }

        return ResponseBuilder::success($collection);
    }

    /**
     * Returns a raw proposal or a blank one.
     *
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function fetchRaw(Request $request)
    {
        $item = Proposal::with(['concepts' => function ($query) {
            return $query->orderBy('order', 'asc');
        }])->find($request->id);
        if (! $item) {
            $item = new Proposal();
            $item->date = date('Y-m-d');
            $item->concepts = [];
        }

        return ResponseBuilder::success($item);
    }

    /**
     * Displays the proposal resource.
     *
     * @param  \App\Proposal  $proposal
     * @return \Illuminate\Http\Response
     */
    public function viewProposal(Request $request)
    {
        $proposal = Proposal::where('id', $request->id)
                    ->where('slug', $request->slug)
                    ->with('client')
                    ->with('concepts')
                    //->with('taxes')
                    ->first();

        if (! $proposal) {
            return redirect()->to('https://genomada.com');
        }

        return view('proposals.view', compact('proposal'));
    }
}

resources/views/proposals/view.blade.php
@php
$config = [
    'appName' => config('app.name'),
    'locale' => $locale = app()->getLocale(),
    'locales' => config('app.locales'),
    'githubAuth' => config('services.github.client_id'),
];
@endphp
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{{ config('app.name') }} / {{ $proposal->name }}</title>

  <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,200;0,400;1,200;1,400&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ mix('dist/css/app.css') }}">

</head>
<body>

    <div class="container">
      <div id="proposal">

        <div class="row mb-5">

          <div class="col-12 col-md-8">
            <h1>{{ $proposal->name }}</h1>
          </div>

          <div class="col-12 col-md-4 text-right">
            <p>
              <strong>{{ $proposal->reference }} · {{ $proposal->show_date }}</strong>
              <br/>{{ $proposal->client->name }}
              <br/>{{ $proposal->contact_person }}
            </p>
          </div>

        </div>

        <div class="row mb-5">
          <div class="col-12">
            {!! $proposal->desc !!}
          </div>
        </div>

        @foreach($proposal->concepts as $concept)
          <div class="row mb-5">
            <div class="col-10">
              <h3>{{ $concept->name }}</h3>
            </div>
            <div class="col-2 text-right">
              <h5 class="price">{{ currency($concept->price) }}</h5>
            </div>
          </div>
          <div class="row mb-5">
            <div class="col-12">
              {!! $concept->desc !!}
            </div>
          </div> 
        @endforeach   

        <div id="proposal-resume">

          <div class="row">
            <div class="col-8">
              <h4 class="mb-3">@lang('genomada.resume')</h4>
            </div>
            <div class="col-2 text-right">
              @lang('genomada.finish_date')
            </div>
            <div class="col-2 text-right">
              @lang('genomada.amount')
            </div>
          </div>

          @foreach($proposal->concepts as $concept)
            <div class="row slot-concept-proposal-resume">
              <div class="col-8">
                <p><strong>{{ $concept->name }}</strong></p>
              </div>
              <div class="col-2 text-right">
                <p>{{ $concept->show_finish_date }}</p>
              </div>
              <div class="col-2 text-right">
                <h5 class="price">{{ currency($concept->price) }}</h5>
              </div>
            </div>
          @endforeach   
        </div> 

        <div class="row mb-5" id="terms">
          <div class="col-12 text-sm">
            <p><strong>@lang('genomada.terms_and_conditions')</strong></p>
            {!! $proposal->terms !!}
          </div>
        </div>

      </div>
    </div>

    <div id="credits-genomada">

      <p>
        <a href="https://genomada.com" target="_blank"><img src="/img/genomada-logo.png"/></a>
      </p>
      <p>
        @lang('genomada.credits')
      </p>

    </div>

</body>
</html>